services:
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - blocks-tracker

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

    networks:
      - blocks-tracker
        
  phpmyadmin: 
    image: phpmyadmin:latest 
    ports: 
      - "127.0.0.1:8080:80"  # Only accessible from localhost
    environment: 
      PMA_HOST: db 
      PMA_PORT: 3306 
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    networks:
      - blocks-tracker


volumes:
  db_data:

networks:
  blocks-tracker:
    name: blocks-tracker
    driver: bridge
